//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EARTH.Jaguar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_NotasPublicas
    {
        public int idNotasPublicas { get; set; }
        public System.DateTime FechaNota { get; set; }
        public string Nota { get; set; }
        public Nullable<System.DateTime> FechaRecordatorio { get; set; }
        public bool Activa { get; set; }
    }
}
