//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EARTH.Jaguar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Notas
    {
        public int IdPersona { get; set; }
        public int idNota { get; set; }
        public string TipoNota { get; set; }
        public string Area { get; set; }
        public System.DateTime FechaNota { get; set; }
        public string Nota { get; set; }
        public Nullable<System.DateTime> FechaRecordatorio { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> Activa { get; set; }
    
        public virtual P_Personas P_Personas { get; set; }
    }
}
