//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EARTH.Jaguar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_Estudiantes
    {
        public R_Estudiantes()
        {
            this.R_RegistroNotas = new HashSet<R_RegistroNotas>();
        }
    
        public int IdPersona { get; set; }
        public string Carrera { get; set; }
        public Nullable<int> Generacion { get; set; }
        public short Grupo { get; set; }
        public Nullable<bool> Suspendido { get; set; }
        public Nullable<int> A_Retiro { get; set; }
        public string U_A_lectivo { get; set; }
        public string U_T_lectivo { get; set; }
        public Nullable<int> A_Ingreso { get; set; }
        public Nullable<int> A_Reingreso { get; set; }
        public bool Pasante { get; set; }
        public bool Reingreso { get; set; }
        public bool Graduado { get; set; }
        public string Estado { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Nacionalidad { get; set; }
        public Nullable<int> PosicionEARTH { get; set; }
        public Nullable<decimal> MontoSeguro { get; set; }
        public string PagoColegiatura { get; set; }
        public bool PAlterno { get; set; }
        public bool LimFinanciera { get; set; }
        public Nullable<int> TrackingId { get; set; }
    
        public virtual P_Personas P_Personas { get; set; }
        public virtual ICollection<R_RegistroNotas> R_RegistroNotas { get; set; }
    }
}
