//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EARTH.Jaguar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VR_Rendimiento_Periodos
    {
        public int A_Adem { get; set; }
        public string Trimestre { get; set; }
        public int Estudiante { get; set; }
        public string Carrera { get; set; }
        public Nullable<int> CursosReprobados { get; set; }
        public Nullable<int> CursosGanados { get; set; }
        public Nullable<decimal> ZPuntosPP { get; set; }
        public Nullable<decimal> zCreditosPP { get; set; }
        public Nullable<decimal> PP { get; set; }
        public Nullable<decimal> CreditosGanados { get; set; }
        public Nullable<int> CursosRecuperados { get; set; }
        public Nullable<int> CursosPosiblesRecuperaciones { get; set; }
        public Nullable<int> CursosParaRecuperacion { get; set; }
        public Nullable<int> CursosPerdidos { get; set; }
        public Nullable<int> CursosRetirados { get; set; }
        public Nullable<int> CursosIncompletos { get; set; }
        public Nullable<int> CursosMatriculados { get; set; }
        public Nullable<int> CursosPendientes { get; set; }
        public Nullable<int> CursosNoRecuperados { get; set; }
        public Nullable<int> CursosNoVanRecuperacion { get; set; }
        public Nullable<int> CursosAprobados { get; set; }
    }
}
